title: GraphAlg
description: "GraphAlg: An embeddable language for graph algorithms"
theme: just-the-docs

url: https://wildarch.dev/graphalg

callouts:
  note:
    title: Note
    color: blue

  warning:
    title: Warning
    color: yellow

  error:
    title: Error
    color: red

  error-titled:
    color: red

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # For this project
  - codemirror-lang-graphalg/
  - compiler/
  - docker/
  - docs/
  - grammars/
  - third-party/
  - website/
  - LICENSE
  - package-lock.json
  - package.json
  - README.md

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
