name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/wildarch/graphalg-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build codemirror-lang-graphalg
        shell: bash
        run: |
          source /root/emsdk/emsdk_env.sh
          npm --workspace=codemirror-lang-graphalg install
          npm --workspace=codemirror-lang-graphalg run prepare
      - name: Build compiler
        shell: bash
        run: |
          ./compiler/configure.sh
          cmake --build ./compiler/build
          cmake --build ./compiler/build --target check
      - name: Build playground
        shell: bash
        run: |
          source /root/emsdk/emsdk_env.sh
          npm --workspace=playground install
          playground/cpp/configure-wasm.sh
          cmake --build playground/cpp/build-wasm --target graphalg-playground
          npm --workspace=playground run prepare
      - name: Build website
        env:
          GEM_HOME: /root/gems
        run: |
          /root/gems/bin/bundle install
          /root/gems/bin/bundle exec jekyll build
