name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/wildarch/graphalg-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build codemirror-lang-graphalg
        run: codemirror-lang-graphalg/ci.sh
      - name: Build compiler (native)
        run: compiler/ci.sh
      - name: Build compiler (wasm)
        run: compiler/ci-wasm.sh
      - name: Build playground
        run: playground/ci.sh
      - name: Build website
        run: ci-website.sh
